version: "3.7"

services:
  backend:
    build: .
    ports: 
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
      - keycloak

  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - '8180:8080'
    image: 'quay.io/keycloak/keycloak:15.0.2'
    volumes:
      - ./src/main/docker/certs:/etc/ssl/certs/java
      - ./src/main/docker/imports:/opt/jboss/keycloak/imports

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

volumes:
  postgres-data:
