@startuml

class Survey{
    id: Long
    question: String
    createDateTime: LocalDateTime
}

class AnswerOption{
    id: Long
    text: String
    survey: Survey
    createDateTime: LocalDateTime
}

class Answer {
    id: Long
    userName: String
    answerOption: AnswerOption
    createDateTime: LocalDateTime
}

Survey <- AnswerOption
AnswerOption <- Answer

@enduml