= Besprechungsprotokoll 29.04.2021
Christine Raffeiner
1.0, 04.07.2021: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Nina Weissengruber
|
|Christine Raffeiner
|


|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|19:05 - 20:10
|Dauer
|1h 5min
|===


== Besprochene Themen
* Wir haben allgemein über die Aufgabenstellung und den Umfang unserer Diplomarbeit gesprochen, da Raffeiner Christine neu zu dem Projekt hinzugekommen ist.
* Danach haben wir in der Diplomarbeitsdatenbank für unsere Themenstellung Meilensteine und die individuellen Themenstellungen festgelegt.
* Anschließend haben wir ein Github-Repository für unsere Diplomarbeit angelegt.

== Nächste Schritte
* Die Erklärung für die Diplomarbeit unterschreiben und auf die Datenbank laden.
* Den Antrag für die Diplomarbeit abgeben.