= Besprechungsprotokoll 01.07.2021
Christine Raffeiner
1.0, 04.07.2021: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Nina Weissengruber
|
|Christine Raffeiner
|


|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|In der Schule

|von-bis
|11:45 - 12:40
|Dauer
|55 min
|===


== Besprochene Themen
* Wir haben unseren Diplomarbeitsantrag umgeändert und dabei eine Zielsetzung hinzugefügt und die individuellen Themenstellungen angepasst.
* Danach haben wir den Funktionsumfang der Diplomarbeit besprochen.
** Gestalten von Fragebögen
** Durchführen von Fragebögen
** Auswerten von Befragungen (exportieren als csv Datei + Standartauswertung)
** Anmelden mittels WebUnits
** Mehrere Fragebögen stehen für alle Benutzer (Fragebogenersteller) zur Verfügung
** Befragungen können anonym (mit TAN und  auch mit Authentisierung / nur einen Fragebogen ausfüllen) oder mit Namen (Authentisierung) oder keine Anmeldung durchgeführt werden.
* Weiters haben wir über den Ablauf der Diplomarbeit gesprochen.
. Datenmodel definieren
. Datenmodell als Java Klassen implementieren
. Use-Cases definieren
. Die einzelnen Use-Cases ohne GUI implementieren
. Endpoints erstellen, welche die Repository-Funktionen verwenden und die die Angular App später verwenden kann
. Implementieren der Authentifizierung und Authorisierung


== Nächste Schritte
* Datenmodell erstellen und bei Professor Stütz melden.