= Besprechungsprotokoll 22.10.2022
Christine Raffeiner
1.0, 13.01.2022: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Christine Raffeiner
|

|Nina Weissengruber
|

|Isabel Turner
|
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Schule

|von-bis
|09:30 - 09:45 / 10:00 - 11:00
|Dauer
|1h 15min
|===


== Besprochene Themen
* Bei der Evaluierung unseres jetzigen Standes der Diplomarbeit sind wir auf einige Ablaufprobleme beim Anlegen von Transactioncodes und Surveys im Dashboard gekommen. Aufgrunddessen soll das Dashboard nochmals überarbeitet werden. Dafür wird eine hirachische Tabelle für die Fragebögen und Befragungen, dieman  filtern kann implementiert.
* Weiteres haben wir darüber gesprochen das für den Anwendungsfall eines Testes mit der Survey ein zusätzliches Attribut bei den AnswerOptions (isTrue) einzufügen.
* Zudem haben wir auch über die Notwendigkeit einer Löschbestätigung für Fragebögen und Befragungen gesprochen.
* Auserdem ist beschlossen worden, wir zurzeit keine Ldap-User impelmentieren müssen. (Login entfällt)
* Abschließend wurde Isabel die Auswertung der Befragung sowohl im Forntend als auch im Backend zugeteilt. Diese soll mithilfe von einer Libary zusätzlich visualisiert werden. (z.B. Chart.js)

== Nächste Schritte
* Die angesprochenen Probleme beheben.
* CLD und import.sql aktualisieren.