= Besprechungsprotokoll 31.08.2021
Christine Raffeiner
1.0, 15.07.2021: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Christine Raffeiner
|

|Nina Weissengruber
|
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|14:00 - 15:50
|Dauer
|1h 50min
|===


== Besprochene Themen
* Zuerst haben wir über unsere GitHub-Branches gesprochen, wobei uns Herr Professor Stütz darauf aufmerksam gemacht hat, dass es bei der jetzigen Lage eventuell zu Konflikten kommen könnte.
* Danach haben wir den Text, der beim Starten des Servers im Terminal angezeigt wird von Quarkus auf HTL Leonding geändert.
* Als Nächstes haben wir alle nicht mehr relevanten Tests mit @Disabled annotiert, sodas sie bei automatischem Start der Tests nicht mehr mit ausgeführt werden.
* Als letztes haben wir uns die erstellten Karate-Test für die Klassen Interviewer, Questionnaire, Question und AnswerOption angesehen. Grundsätzlich sind die Tests in Ordnung, doch die Tests sollten noch ausgebaut werden.

== Nächste Schritte
* Bei den Methoden auch auf nicht mögliche Requests testen (z.B. Löschen eines nicht vorhandenen Interviewers) und daraufhin passenden Fehlermeldungen mit aussagekräftigen Fehlercodes zurückgeben.
* Für den jetzigen Teil einen Angular-Client ohne Authentifizierung bzw. Autorisierung erstellen und schrittweise mit dem Backend erweitern.
* In kleinen Schritten die weiteren Karate-Tests für die Klassen erstellen und testen.
* Frau Isabell Turner muss Tests für die Repositories der Klassen InterviewerRepository, QuestionnnaireRepository und QuestionRepository erstellen.
