= Besprechungsprotokoll 09.08.2021
Christine Raffeiner
1.0, 15.07.2021: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Nina Weissengruber
|

|Christine Raffeiner
|
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|20:00 - 21:50
|Dauer
|1h 50min
|===


== Besprochene Themen
* Zuerst haben wir Imports bei unseren Tests ausgetauscht.
* Danach haben wir unsere Probleme mit AssertJ-db-Tests angesprochen und anschließend einen solchen Test gemeinsam programmiert.
* Daraufhin haben wir uns darauf geeinigt den vorhandenen Test (Test für Repositories) nicht mehr so genau zu testen und uns auf die Testung der Rest-Schnittstellen zu konzentrieren.
* Wir haben beschlossen die Rest-Schnittstellen mit Karate-junit5 zu testen und haben diese Library daraufhin implementiert.
* Danach haben wir eine Erklärung zu Karate erhalten und angefangen einen einfachen Test zu implementieren.

== Nächste Schritte
* Rest-Schnittstellen und Tests (HTTP-File) für das Speichern von einem Interviewer und einem Questionnaire erstellen. Danach bei Herr Professor Stütz melden (evtl. Änderungen vornehmen) und danach die restlichen Schnittstellen für die restlichen Klassen implementieren.
* YouTrack Tasks für jede Klasse erstellen.