-- Lehrer Feedbackbogen
insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen für Lehrer',true, 'HTL Leonding');

insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist fair - gerecht', 1, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist humorvoll - fröhlich', 2, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist hilfsbereit - unterstützend', 3, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist freundlich', 4, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist engagiert - aktiv', 5, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist verständnisvoll', 6, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist ehrlich - aufrichtig', 7, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist kooperativ - kontaktfreudig', 8, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist tolerant - lässt Kritik zu', 9, 0, 1);

insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er kann auch schwierige Fragen beantworten, weil er sich in seinem Fachgebiet gut auskennt.', 10, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Für eine gute Note ist es am wichtigsten, wie sympathisch man dem Lehrer ist - die Leistung ist Nebensache.', 11, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich denke, dieser Lehrer kennt mich persönlich schon sehr gut, sowohl in meinen Stärken wie in meinen Schwächen.', 12, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er bemüht sich, uns der Leistung und dem Benehmen entsprechend zu loben weder zu ermahnen und niemanden zu bevorzugen.', 13, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Bei diesem Lehrer ist mir oft nicht klar, worauf es bei seinen Prüfungen ankommt oder wie meine Note zustande kommt.', 14, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich glaube, dass ich durch seinen Unterricht schon viel Neues gelernt habe.', 15, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sein Unterricht ist interessant und attraktiv, weil er sich um Abwechslung und Praxisnähe bemüht.', 16, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er verlangt häufig zuviel von uns und deswegen fühle ich mich beim Lernen oft überfordert und gestresst.', 17, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer erklärt im Unterricht so verständlich und klar, dass ich alles Wichtige gut verstehe und begreife.', 18, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich einen Fehler mache oder mich schlecht benehme, werde ich von diesem Lehrer vor der ganzen Klasse beschimpft oder lächerlich gemacht.',  19, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich freue mich, wenn dieser Lehrer zum Unterricht in unsere Klasse kommt.', 20, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er erklärt uns oft, wie der Lehrnstoff mit anderen Fächern oder mit praktischen Problemen zusammenhängt.', 21, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich bei ihm etwas richtig oder gut gemacht habe, so werde ich dafür auch entsprechend gelobt.', 22, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Bevor er Hausübungen oder etwas zu lernen aufgibt, erkundigt er sich, ob wir schon andere Hausübungen erhalten haben oder Prüfungen bevor stehen.',  23, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er freut sich, wenn es ihm gelungen ist uns etwas Neues oder Schwieriges beizubringen.', 24, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Dieser Lehrer schafft es oft nicht, die zum Arbeiten nötige Ruhe und Ordnung in unserer Klasse herzustellen.', 25, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich Schwierigkeiten beim Lernen habe, kann ich auf die Hilfe und das Verständnis des Lehrers zählen.', 26, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er bemüht sich sehr, uns in seinem Fah auch aktuelle, moderne und lebensnahe Informationen und Beispiele zu geben.', 27, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich einen guten Einfall habe und etwas sagen will, dann beachtet mich der Lehrer oft gar nicht.', 28, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Durch sein Engagement und seinen Einsatz gelingt es dem Lehrer uns für sein Fach besonders zu interessieren und zu aktivieren.', 29, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer achtet darauf, dass wir Schüler im Unterricht auch unsere eigenen Ideen verwirklichen können.', 30, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn mich bei diesem Lehrer etwas stört, so kamm ich das offen sagen, ohne dass ich nachteile befürchten muss.', 31, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Dieser Lehrer beschäftigt sich hauptsächlich mit den guten SchülerInnen in der Klasse.', 32, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn er Hausübungen gibt, dann kann ich diese normalerweise selbstständig und ohne Hilfe anderer Personen bewältigen. ', 33, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich etwas falsch mache - zum Beispiel bei der Hausübung - dann erklärt er mir genau, wie man es richtig macht.', 34, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er bringt mir in diesem Fach etwas bei, was für mich im späteren Leben oder im Beruf wichtig sein wird.', 35, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Durch hohen Lernanforderungen des Lehrers habe ich oft große Angst, bei seinen Prüfungen zu versagen.', 36, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Noten, die ich bei diesem Lehrer bekomme, entsprechen meinen tatsächlichen Leistungen.', 37, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich würde mir wünschen, dass mich dieser Lehrer auch im nächsten Jahr wieder unterrichtet.', 38, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Dieser Lehrer ist mir sympathisch.', 39, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wie zufrieden bist du mit diesem Lehrer insgesamt?', 40, 0, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An diesem Lehrer gefällt mir,', 41, 3, 1);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An diesem Lehrer stört mich,', 42, 3, 1);

insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 1);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 1);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 1);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 1);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 2);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 2);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 2);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 2);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 3);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 3);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 3);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 3);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 4);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 4);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 4);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 4);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 5);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 5);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 5);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 5);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 6);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 6);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 6);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 6);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 7);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 7);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 7);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 7);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 8);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 8);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 8);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 8);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 9);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 9);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 9);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 9);

insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 10);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 10);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 10);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 10);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 11);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 11);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 11);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 11);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 12);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 12);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 12);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 12);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 13);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 13);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 13);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 13);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 14);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 14);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 14);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 14);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 15);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 15);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 15);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 15);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 16);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 16);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 16);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 16);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 17);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 17);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 17);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 17);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 18);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 18);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 18);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 18);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 19);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 19);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 19);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 19);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 20);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 20);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 20);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 20);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 21);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 21);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 21);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 21);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 22);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 22);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 22);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 22);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 23);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 23);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 23);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 23);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 24);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 24);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 24);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 24);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 25);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 25);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 25);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 25);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 26);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 26);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 26);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 26);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 27);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 27);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 27);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 27);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 28);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 28);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 28);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 28);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 29);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 29);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 29);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 29);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 30);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 30);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 30);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 30);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 31);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 31);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 31);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 31);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 32);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 32);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 32);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 32);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 33);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 33);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 33);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 33);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 34);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 34);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 34);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 34);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 35);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 35);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 35);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 35);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 36);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 36);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 36);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 36);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 37);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 37);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 37);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 37);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 38);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 38);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 38);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 38);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 39);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 39);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 39);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 39);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-)', 5, 1, false, 40);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-]', 4, 2, false, 40);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-|', 3, 3, false, 40);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-[', 2, 4, false, 40);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-(', 1, 5, false, 40);

-- Lehrerinnen Feedbackbogen
insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Lehrerinnen-Feedbackbogen', 'Feedbackbogen für Lehrerinnen',true, 'HTL Leonding');

insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist fair - gerecht', 1, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist humorvoll - fröhlich', 2, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist hilfsbereit - unterstüzend', 3, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist freundlich', 4, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist engagiert - aktiv', 5, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist verständnisvoll', 6, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist ehrlich - aufrichtig', 7, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist kooperativ - kontaktfreudig', 8, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerin ist tolerant - lässt kritik zu', 9, 0, 2);

insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie kann auch schwierige Fragen beantworten, weil sie sich in ihrem Fachgebiet gut auskennt.', 10, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Für eine gute Note ist es am wichtigsten, wie sympathisch man der Lehrerinn ist - die Leistung ist Nebensache.', 11, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich denke, diese Lehrerinn kennt mich persönlich schon sehr gut, sowohl in meinen Stärken wie in meinen Schwächen.', 12, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie bemüht sich, uns der Leistung und dem Benehmen entsprechend zu loben oder zu ermahnen und niemanden zu bevorzugen.', 13, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Bei dieser Lehrerinn ist mir oft nicht klar, worauf es bei seinen Prüfungen ankommt oder wie meine Note zu stande kommt.', 14, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich glaube, dass ich durch ihren Unterricht schon viel Neues gelernt habe.', 15, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ihr Unterricht ist interessant und attraktiv, weil er sich um Abwechslung und Praxisnähe bemüht.', 16, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie verlangt häufig zuviel von uns, und deswegen fühle ich mich beim Lernen oft überfordert und gestresst.', 17, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerinn erklärt im Unterricht so verständlich und klar, dass ich alles Wichtige gut verstehe und begreife.', 18, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich einen Fehler mache oder mich schlecht benehme, werde ich von dieser Lehrerinn vor der ganzen Klasse beschimpft oder lächerlich gemacht.', 19, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich freue mich, wenn diese Lehrerinn zum Unterricht in unsere Klasse kommt.', 20, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie erklärt uns oft, wie der Lehrnstoff mit anderen Fächern oder mit praktischen Problemen zusammenhängt.', 21, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich bei ihr etwas richtig oder gut gemacht habe, so werde ich dafür auch entsprechend gelobt.', 22, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Bevor sie Hausübungen oder etwas zu lernen aufgibt, erkundigt er sich, ob wir schon andere Hausübungen erhalten haben oder Prüfungen bevor stehen.', 23, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie freut sich, wenn es ihr gelungen ist uns etwas Neues oder Schwieriges beizubringen.', 24, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Diese Lehrerinn schafft es oft nicht, die zum Arbeiten nötige Ruhe und Ordnung in unserer Klasse herzustellen.', 25, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich Schwierigkeiten beim Lernen habe, kann ich auf die Hilfe und das Verständnis der Lehrerinn zählen.', 26, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie bemüht sich sehr, uns in seinem Fach auch aktuelle, moderne und lebensnahe Informationen und Beispiele zu geben.', 27, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich einen guten Einfall habe und etwas sagen will, dann beachtet mich die Lehrerinn oft gar nicht.', 28, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Durch ihr Engagement und seinen Einsatz gelingt es der Lehrerinn uns für sein Fach besonders zu interessieren und zu aktivieren.', 29, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Lehrerinn achtet darauf, dass wir Schüler im Unterricht auch unsere eigenen Ideen verwirklichen können.', 30, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn mich bei dieser Lehrerinn etwas stört, so kann ich das offen sagen, ohne dass ich nachteile befürchten muss.', 31, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Diese Lehrerinn beschäftigt sich hauptsächlich mit den guten SchülerInnen in der Klasse.', 32, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn sie Hausübungen gibt, dann kann ich diese normalerweise selbstständig und ohne Hilfe anderer Personen bewältigen. ', 33, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wenn ich etwas falsch mache - zum Beispiel bei der Hausübung - dann erklärt sie mir genau, wie man es richtig macht.', 34, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Sie bringt mir in diesem Fach etwas bei, was für mich im späteren Leben oder im Beruf wichtig sein wird.', 35, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Durch hohen Lernanforderungen der Lehrerinn habe ich oft große Angst, bei ihren Prüfungen zu versagen.', 36, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Die Noten, die ich bei dieser Lehrerinn bekomme, entsprechen meinen tatsächlichen Leistungen.', 37, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich würde mir wünschen, dass mich diese Lehrerinn auch im nächsten Jahr wieder unterrichtet.', 38, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Diese Lehrerinn ist mir sympathisch.', 39, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wie zufrieden bist du mit dieser Lehrerinn insgesamt?', 40, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An dieser Lehrerin gefällt mir,', 41, 3, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An dieser Lehrerin stört mich,', 42, 3, 2);

insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 43);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 43);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 43);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 43);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 44);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 44);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 44);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 44);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 45);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 45);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 45);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 45);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 46);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 46);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 46);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 46);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 47);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 47);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 47);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 47);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 48);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 48);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 48);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 48);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 49);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 49);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 49);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 49);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 50);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 50);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 50);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 50);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft völlig zu', 4, 1, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher zu', 3, 2, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft eher nicht zu', 2, 3, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('trifft gar nicht zu', 1, 4, false, 51);

insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 51);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 52);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 52);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 52);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 52);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 53);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 53);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 53);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 53);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 54);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 54);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 54);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 54);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 55);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 55);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 55);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 55);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 56);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 56);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 56);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 56);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 57);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 57);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 57);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 57);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 58);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 58);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 58);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 58);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 59);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 59);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 59);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 59);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 60);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 60);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 60);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 60);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 61);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 61);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 61);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 61);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 62);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 62);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 62);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 62);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 63);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 63);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 63);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 63);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 64);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 64);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 64);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 64);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 65);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 65);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 65);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 65);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 66);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 66);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 66);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 66);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 67);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 67);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 67);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 67);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 68);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 68);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 68);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 68);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 69);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 69);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 69);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 69);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 70);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 70);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 70);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 70);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 71);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 71);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 71);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 71);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 72);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 72);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 72);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 72);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 73);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 73);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 73);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 73);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 74);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 74);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 74);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 74);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 75);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 75);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 75);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 75);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 76);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 76);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 76);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 76);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 77);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 77);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 77);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 77);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 78);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 78);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 78);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 78);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 79);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 79);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 79);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 79);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 80);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 3, 2, false, 80);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 2, 3, false, 80);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 1, 4, false, 80);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-)', 5, 1, false, 81);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-]', 4, 2, false, 81);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-|', 3, 3, false, 81);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-[', 2, 4, false, 81);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-(', 1, 5, false, 81);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-)', 5, 1, false, 82);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-]', 4, 2, false, 82);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-|', 3, 3, false, 82);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-[', 2, 4, false, 82);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values (':-(', 1, 5, false, 82);

-- Interviewer
insert into s_interviewer(i_name) values ('Thomas Stütz');
insert into s_interviewer(i_name) values ('Isabel Turner');
insert into s_interviewer(i_name) values ('Christine Raffeiner');
insert into s_interviewer(i_name) values ('Nina Weissengruber');

--Questionnaire
insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen 4AHITM', false, 'Nina Weissengruber');
insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Maturareiseziel-Fragebogen', 'Maturareise Fragebogen 5AHITM', false, 'Christine Raffeiner');
insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen 5AHITM', false, 'Thomas Stütz');
insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen 2BHITM', false, 'Thomas Stütz');

--Question
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Er kann auch schwierige Fragen beantworten, weil er sich in seimen Fachgebiet gut auskennt?', 1, 0, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Für eine gute Note ist es wichtig wie sympatisch man dem Lehrer ist - die Leistung ist nebensächlich?', 2, 2, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An diesem Lehrer stört mich?', 3, 3, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer ist...', 4, 1, 2);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ziel der Maturareise ist?', 1, 0, 3);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Wie viel Geld kann höchstens ausgegeben werden?', 2, 0, 3);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An diesem Lehrer gefällt mir?', 1, 3, 4);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich freue mich wenn dieser Lehrer zum Unterricht in die Klasse kommt?', 2, 2, 4);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Ich glaube, dass ich durch seinen Unterricht schon viel Neues gelernt habe?', 3, 0, 4);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Der Lehrer erklärt den Unterricht verständlich', 1, 2, 5);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('Das möchte ich zu dem Lehrer anmerken', 2, 3, 5);
insert  into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('An diesem Lehrer gefällt mir nicht?', 3, 3, 5);

--AnswerOption
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 85);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 2, 2, false, 85);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 1, 3, false, 85);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 0, 4, false, 85);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('YES', 1, 1, false, 86);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('NO', 0, 2, false, 86);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('fair - gerecht', 0, 1, false, 88);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('humorvoll - fröhlich', 0, 2, false, 88);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('hilfsbereit - unterstützend', 0, 3, false, 88);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('freundlich', 0, 4, false, 88);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('engagiert - aktiv', 0, 5, false, 88);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('verständnisvoll - rücksichtsvoll', 0, 6, false, 88);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('Kroatien', 0, 1, false, 89);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('Spanien', 0, 2, false, 89);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('Italien', 0, 3, false, 89);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('über 500', 0, 1, false, 90);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('unter 500', 0, 2, false, 90);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('YES', 1, 1, false, 92);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('NO', 0, 2, false, 92);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig richtig', 4, 1, false, 93);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher richtig', 2, 2, false, 93);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('eher falsch', 1, 3, false, 93);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('völlig falsch', 0, 4, false, 93);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('YES', 1, 1, false, 94);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('NO', 0, 2, false, 94);

--Answer
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('völlig richtig', 85, null);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('völlig richtig', 93, null);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('YES', 86, null);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('NO', 92, null);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('YES', 94, null);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('Nix eigentlich',91, null );
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('Mich stört das der Lehrer immer zu spät kommt', 87, null);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('Der Lehrer überzieht immer den Unterricht', 96, null );

--ChosenOption
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (1, 1, 85);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (2, 1, 93);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (8, null, 87);

--Survey
insert into s_survey(s_title, s_description, s_i_id, s_qn_id, s_date, s_survey_conducted) values ('Befragung', 'Befragung for class', 'Isabel Turner', 2, current_date, false);
insert into s_survey(s_title, s_description, s_i_id, s_qn_id, s_date, s_survey_conducted) values ('Befragung', 'Befragung for class', 'Thomas Stütz', 2, current_date, false);
insert into s_survey(s_title, s_description, s_i_id, s_qn_id, s_date, s_survey_conducted) values ('Befragung', 'Befragung for class', 'Christine Raffeiner', 2, current_date, false);

insert into S_TRANSACTION(TR_TRANSACTION_CODE, TR_IS_USED, T_S_ID) values ('1003-2202-abcd', false, 1);
insert into S_TRANSACTION(TR_TRANSACTION_CODE, TR_IS_USED, T_S_ID) values ('1001-2012-abcd', false, 1);




insert into s_questionnaire(qn_name, qn_descr, qn_is_public, qn_i_id) values ('Questionnaire 1', 'Feedbackbogen für Lehrer', false, 'Weissengruber Nina');

insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('question 1', 1, 0, 7);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('question 2', 2, 0, 7);
insert into s_question(q_text, q_sequence_number, q_type, q_qn_id) values ('freetext', 2, 3, 7);

insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('answeroption 1', 1, 1, false, 97);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('answeroption 2', 2, 2, false, 97);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('answeroption 3', 1, 3, false, 98);
insert into s_answer_option(ao_text, ao_value, ao_sequence_number, ao_is_correct_answer, ao_q_id) values ('answeroption 4', 2, 4, false, 98);

insert into s_survey(s_title, s_description, s_i_id, s_qn_id, s_date, s_survey_conducted) values ('Fragebogen', 'Befragung for class', 'Isabel Turner', 7, current_date, false);

insert into S_TRANSACTION(TR_TRANSACTION_CODE, TR_IS_USED, T_S_ID) values ('1001-2012-aaaa', true, 4);
insert into S_TRANSACTION(TR_TRANSACTION_CODE, TR_IS_USED, T_S_ID) values ('1001-2012-bbbb', true, 4);
--insert into S_TRANSACTION(TR_TRANSACTION_CODE, TR_IS_USED, T_S_ID) values ('1001-2012-cccc', true, 4);

insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('answer', 97, 3);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('answer', 97, 4);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('answer', 98, 3);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('answer', 98, 4);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('Mich stört das der Lehrer immer zu spät kommt', 99, 4);
insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('Mich stört ', 99, 3);
--insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('answer', 97, 3);
--insert into s_answer(a_answer_text, a_q_id, a_tr_id) values ('answer', 98, 4);

insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (9, 353, 97);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (10, 353, 97);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (11, 355, 98);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (12, 356, 98);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (13, null, 99);
insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (14, null, 99);
--insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (15, 354, 97);
--insert into s_chosen_option(co_a_id, co_ao_id, co_q_id) values (16, 356, 98);

